'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Mic, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import FileUpload from '@/components/shared/file-upload';
import ProcessingJobStatus from '@/components/tools/processing-job-status';
import { useProcessingSubmit } from '@/hooks/use-processing-submit';

export default function TranscribePage(){const[file,setFile]=useState<File|null>(null);const[model,setModel]=useState('tiny');const{jobId,submitting,error,submit}=useProcessingSubmit('/api/worker/tools/transcribe');const run=async()=>{if(!file)return;const body=new FormData();body.append('file',file);body.append('model',model);if(await submit(body))setFile(null);};return <div className="space-y-6 max-w-2xl"><Link href="/tools" className="inline-flex items-center gap-1 text-xs text-slate-500"><ArrowLeft className="h-4 w-4"/>Back to Tools</Link><h1 className="flex items-center gap-2 text-2xl font-bold"><Mic className="h-6 w-6 text-indigo-600"/>AI Transcription</h1><div className="space-y-5 rounded-2xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><FileUpload onFileSelect={setFile} selectedFile={file} accept={{'audio/*':['.mp3','.wav','.flac','.ogg','.m4a'],'video/*':['.mp4','.mkv','.webm','.mov','.avi']}} label="Drop audio or video to transcribe" hint="Requires the optional AI worker profile"/>{file&&<><select className="w-full rounded-lg border p-2 dark:bg-slate-800" value={model} onChange={(e)=>setModel(e.target.value)}><option value="tiny">Tiny</option><option value="base">Base</option><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select><Button className="w-full" disabled={submitting} onClick={run}>{submitting?'Uploading…':'Transcribe'}</Button></>}{error&&<p className="flex items-center gap-2 text-sm text-red-600"><AlertCircle className="h-4 w-4"/>{error}</p>}<ProcessingJobStatus jobId={jobId}/></div></div>;}
